# Generated by Django 4.1.1 on 2024-02-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursePortal', '0002_alter_contact_date_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('mrp', models.FloatField()),
                ('faculty_name', models.CharField(max_length=50)),
                ('duration', models.TimeField()),
                ('intake', models.IntegerField()),
            ],
        ),
    ]
