# Generated by Django 4.1.1 on 2024-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursePortal', '0003_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(),
        ),
    ]
