# Generated by Django 4.1.1 on 2024-02-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursePortal', '0008_course_category_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('web_design', 'Web Design'), ('graphics_design', 'Graphic design'), ('video_editing', 'Video Editing'), ('online_marketing', 'Online Marketing')], default='web_design', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
    ]
