# Generated by Django 5.0.1 on 2024-02-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursePortal', '0010_enrollment_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
